# ============================================================
# DLBCL Tumor-Only WES Pipeline — Configuration
# ============================================================


# ------------------------------------------------------------
# Reference genome (GRCh38)
# ------------------------------------------------------------

reference: "reference/GRCh38.fa"

# ------------------------------------------------------------
# Mutect2 resources
# ------------------------------------------------------------

# gnomAD germline resource
germline_resource: "reference/germline/af-only-gnomad.hg38.vcf.gz"

# Common variants for contamination estimation
common_variants: "reference/germline/small_exac_common_3.hg38.vcf.gz"

# Optional Panel of Normals
# Leave empty if not available
panel_of_normals: ""
# ------------------------------------------------------------
# Computational resources
# ------------------------------------------------------------
threads:
  fastqc: 4
  trimmomatic: 2
  bwa: 16
  gatk: 8
  vep: 8

# ------------------------------------------------------------
# Trimmomatic
# ------------------------------------------------------------
trimmomatic:
  adapters: "reference/adapters/NexteraPE-PE.fa"

# ------------------------------------------------------------
# VEP configuration
# ------------------------------------------------------------
# IMPORTANT:
# This is the directory ABOVE homo_sapiens/
# NOT the 115_GRCh38 folder itself

vep_cache: "reference"

vep_plugins_dir: "reference/vep_plugins"

# ------------------------------------------------------------
# VEP plugins
# ------------------------------------------------------------
vep_plugins:

  # CADD
  #cadd_snv: "reference/CADD/whole_genome_SNVs.tsv.gz"
  #cadd_indels: "reference/CADD/InDels.tsv.gz"

  # REVEL
   #revel: "reference/REVEL/new_tabbed_revel_grch38.tsv.gz"

  # AlphaMissense
  #alphamissense: "reference/AlphaMissense/AlphaMissense_hg38.tsv.gz"

  # ClinVar
  clinvar_vcf: "reference/clinvar/clinvar_GRCh38.vcf.gz"
# ------------------------------------------------------------
# Variant prioritization thresholds
# ------------------------------------------------------------
thresholds:

  # CADD PHRED score cutoff
  cadd_phred: 20

  # REVEL score cutoff
  revel: 0.5
# ------------------------------------------------------------
# DLBCL driver genes
# ------------------------------------------------------------
dlbcl_driver_genes:

  - KMT2D
  - TP53
  - BCL6
  - CREBBP
  - MYD88
  - CD79B
  - EZH2
  - PIM1
  - TNFRSF14
  - GNA13
  - B2M
  - CD58
  - SOCS1
  - TNFAIP3
  - BTG2
  - DTX1
  - MEF2B
  - PRDM1
  - STAT6
  - NOTCH1
  - NOTCH2
  - FOXO1
  - CCND3
  - TBL1XR1
